### ISSUE TITLE
Error at running /api-platform-samples/sample-proxies/oauth-advanced/login-app/deploy.sh

### ISSUE THREAD

**Issue by DImuthuUpe** [apigee/api-platform-samples#44]
When I try to run ./deploy.sh  in ./api-platform-samples/sample-proxies/oauth-advanced/login-app
it gives following error 
Error: Error: NPM install failed with status code 504

But when look at the server I can see the login-app has been created. What is the reason for that?

**Comment by WWitman** [comment]
I just reproduced this error message. The proxy did get uploaded, but not deployed on Edge, which isn't the desired behavior. The error is caused by a timeout on Edge when the Node.js modules are deploying. In the deploy.sh file, apigeetool is called with the -R option. By changing it to -U, the error goes away, and the proxy deploys properly. See the apigeetool docs here for details on these flags: https://www.npmjs.com/package/apigeetool. I'll change the script to -U to hopefully avoid this for others.
