### ISSUE TITLE
ERROR in /learn-edge/provisioning with ./setup.sh

### ISSUE THREAD

**Issue by smarandache1990** [apigee/api-platform-samples#82]
error : ./setup.sh: 4: ./setup.sh: source: not found
line 4 of setup script:   source ../../setup/userconf.sh || exit 1
userconf.sh does exist with in setup <dir>. how could i go about fixing this?

**Comment by WWitman** [comment]
@smarandache1990 I just successfully deployed and invoked one of the learn-edge examples. I'd like to help you get past this error and figure out what the problem is. I think more information would help me troubleshoot. What OS are you using? What steps were you doing when you got these errors? Which sample from learn-edge were you trying to run? Any additional information would be helpful. Thanks!
